### PR TITLE
Allow react@17 as a peer dependency

### PR DESCRIPTION
**Pull request by elliottsj**

### CODE REVIEW

**Comment by electerious** [comment]
Thanks!

I've never seen `||` in a package.json. Is this really a thing? Requiring `^17.0.0` only would be fine, too.

**Comment by elliottsj** [comment]
Yep, it's part of semver! https://jubianchi.github.io/semver-check/#/^16.0.0%20||%20^17.0.0/17.1.2

I'd be fine with `^17.0.0` as well, but there may be some people still stuck on 16.

**Comment by electerious** [comment]
Released as 3.0.0 😊

**Comment by nareshpingale** [comment]
It would be ideal to keep support for all version.

```
"react": "^16.8.0 || ^17.0.0 || ^18.0.0",
```

Adding a PR for same. #10

**Pull request merged**
